import type { PadResult } from "./types";

// Stand-in for GET /api/results (PRD §8.1) — one representative wrapper-off
// run per level, shaped to make the 2x2 legible on first look. Swap this
// module for a fetch of the real data/results.json once the server (Farill)
// and levels config (Georgio) exist; nothing else in gameview/ depends on
// where this array comes from.
export const MOCK_RESULTS: PadResult[] = [
  {
    levelId: 1,
    mechanic: "silent_validation",
    variant: 1,
    agentName: "browser-use",
    model: "claude-sonnet-5",
    claimed: true,
    actual: false,
    orderIdReturned: "ORD-PENDING",
    durationS: 58,
    llmCostUsd: 0.04,
    rejectedClaims: 0,
    duplicateOrders: false,
    wrapperEnabled: false,
  },
  {
    levelId: 2,
    mechanic: "silent_validation",
    variant: 2,
    agentName: "raw-loop",
    model: "claude-sonnet-5",
    claimed: true,
    actual: false,
    orderIdReturned: "ORD-PENDING",
    durationS: 71,
    llmCostUsd: 0.06,
    rejectedClaims: 0,
    duplicateOrders: false,
    wrapperEnabled: false,
  },
  {
    levelId: 3,
    mechanic: "fake_confirmation",
    variant: 1,
    agentName: "browser-use",
    model: "claude-sonnet-5",
    claimed: true,
    actual: false,
    orderIdReturned: null,
    durationS: 41,
    llmCostUsd: 0.03,
    rejectedClaims: 0,
    duplicateOrders: false,
    wrapperEnabled: false,
  },
  {
    levelId: 4,
    mechanic: "fake_confirmation",
    variant: 2,
    agentName: "raw-loop",
    model: "claude-sonnet-5",
    claimed: true,
    actual: false,
    orderIdReturned: "ORD-9F3A21C0",
    durationS: 49,
    llmCostUsd: 0.04,
    rejectedClaims: 0,
    duplicateOrders: false,
    wrapperEnabled: false,
  },
  {
    levelId: 5,
    mechanic: "optimistic_ui",
    variant: 1,
    agentName: "browser-use",
    model: "claude-sonnet-5",
    claimed: true,
    actual: false,
    orderIdReturned: "ORD-PENDING",
    durationS: 52,
    llmCostUsd: 0.05,
    rejectedClaims: 0,
    duplicateOrders: false,
    wrapperEnabled: false,
  },
  {
    levelId: 6,
    mechanic: "optimistic_ui",
    variant: 2,
    agentName: "raw-loop",
    model: "claude-sonnet-5",
    claimed: true,
    actual: true,
    orderIdReturned: "ORD-4B7E10AA",
    durationS: 88,
    llmCostUsd: 0.09,
    rejectedClaims: 0,
    duplicateOrders: false,
    wrapperEnabled: false,
  },
  {
    levelId: 7,
    mechanic: "payload_tampering",
    variant: 1,
    agentName: "browser-use",
    model: "claude-sonnet-5",
    claimed: false,
    actual: true,
    orderIdReturned: "ORD-2C61FEB3",
    durationS: 103,
    llmCostUsd: 0.11,
    rejectedClaims: 0,
    duplicateOrders: true,
    wrapperEnabled: false,
  },
  {
    levelId: 8,
    mechanic: "payload_tampering",
    variant: 2,
    agentName: "raw-loop",
    model: "claude-sonnet-5",
    claimed: true,
    actual: false,
    orderIdReturned: "ORD-77D40E19",
    durationS: 64,
    llmCostUsd: 0.07,
    rejectedClaims: 0,
    duplicateOrders: false,
    wrapperEnabled: false,
  },
  {
    levelId: 9,
    mechanic: "dom_instability",
    variant: 1,
    agentName: "browser-use",
    model: "claude-sonnet-5",
    claimed: true,
    actual: true,
    orderIdReturned: "ORD-1A5C88D2",
    durationS: 37,
    llmCostUsd: 0.03,
    rejectedClaims: 0,
    duplicateOrders: false,
    wrapperEnabled: false,
  },
  {
    levelId: 10,
    mechanic: "dom_instability",
    variant: 2,
    agentName: "raw-loop",
    model: "claude-sonnet-5",
    claimed: true,
    actual: false,
    orderIdReturned: null,
    durationS: 45,
    llmCostUsd: 0.04,
    rejectedClaims: 0,
    duplicateOrders: false,
    wrapperEnabled: false,
  },
  {
    levelId: 11,
    mechanic: "injection",
    variant: 1,
    agentName: "browser-use",
    model: "claude-sonnet-5",
    claimed: true,
    actual: true,
    orderIdReturned: "ORD-C930F71E",
    durationS: 66,
    llmCostUsd: 0.06,
    rejectedClaims: 0,
    duplicateOrders: false,
    wrapperEnabled: false,
  },
  {
    levelId: 12,
    mechanic: "injection",
    variant: 2,
    agentName: "raw-loop",
    model: "claude-sonnet-5",
    claimed: false,
    actual: false,
    orderIdReturned: null,
    durationS: 39,
    llmCostUsd: 0.03,
    rejectedClaims: 0,
    duplicateOrders: false,
    wrapperEnabled: false,
  },
];
